language: python
python:
- '3.6'
sudo: false
git:
  submodules: false
script: echo "done"
deploy:
  provider: pypi
  user: trafficsense
  on:
    branch: master
  password:
    secure: M3gq5gzAGuonvIF3fdf7YlZjOigQA874r0QdqC/gbjCOVIjkv1Mbpa6Fu8o8i5YOvB/UKHdy8LUHr/OCb2KyTH+hsKjBiuMD2w13WijfSmat24uy6hxVY2iTjVDcYMfGneF+bXlalAb346HYQFnqWj32u4IQI+a2uvOGSRzCiLTIK9BRtcP48l+LMlHWBW2QRFaDY2c38ugpt0WjKpJzUL++T6fvfQIWAWmfPX13gBIoK/0HPLryfnmv1rzu4iJzGGsTqnrowIcaTVDgy8upeKY3RhuqPvj5j3bHV4X8D3PJRcHAVGv+0GtDBr4E8XLARYUnKrFDRPGOaiCaioXCr2tJLiLTPt20OIL4gS48nE6HxJ9FGEVysSrgNYmntJ32nzysAjMiD8cHg0G1JhX+ax2o6tDoUyU+rTjw4FXI4WZq9770wx7peAi/+gkv8+9I004ZkEwvoaxJb8ARZuapV4o5tOmj82ZQjef9Q7vz8e7OtCLaRhL5d9k8UwTke3mm9z6fmzWfWhDXywSjQpa8AOwNbJykMM6a3Os1m9kbnRZ2gngG3Pj3jKxRC47bOVVXOR2T+sK6EkPOpN/38Aa6Rn9O6H/4isiKju/5V3VS2CzLxjrR8zwEPwBWc1KMXZJ76RoCtiUNaVa6/U0XDFSCFlV7lCh8wPI4jk8TeMoCeAY=
